### ISSUE TITLE
Add-on by Sting-ray

### ISSUE THREAD

**Issue by johnsonsirv** [johnsonsirv/local-restaurant-page#3]
Please leave a comment here

**Comment by shjang7** [comment]
That's great to use HtmlWebpackPlugin template to navigate menus.

**Comment by grace-mugoiri** [comment]
Since your application is based on Nigerian dish, you can add price in 'Naira' as well which your the national currency.

**Comment by johnsonsirv** [comment]
Thank you, team, @shjang7 @grace-mugoiri for the feedback
